"""Generates the Assay CSS files from design-system/tokens.json.

tokens.css defines every token as a CSS custom property (--rf-*). Theme and
status colors use light-dark(), so they follow the operating system's color
scheme unless an ancestor sets data-theme="light" or data-theme="dark".

tailwind.css is a Tailwind CSS v4 theme that maps utility names onto those
properties, so every value lives in tokens.json and nowhere else.

The build refuses to write the files if a text, control or focus color pair
falls below WCAG AA contrast in either theme.

Usage, from the repository root:

    python design-system/build_tokens.py          # regenerate both files
    python design-system/build_tokens.py --check  # exit 1 if either is stale
"""

import argparse
import json
import pathlib
import re
import sys

DESIGN_DIR = pathlib.Path(__file__).resolve().parent
TOKENS_PATH = DESIGN_DIR / "tokens.json"
EXTENSION_KEY = "org.ragfoundry"
TEXT_CONTRAST = 4.5
NON_TEXT_CONTRAST = 3.0

# Foreground and background theme colors that must reach TEXT_CONTRAST.
# Every status adds its own fg-on-bg pair; see contrast_requirements().
_TEXT_PAIRS = (
    ("fg", "bg"),
    ("fg", "surface"),
    ("fg", "surface-raised"),
    ("fg", "surface-sunken"),
    ("fg", "evidence-highlight"),
    ("fg-secondary", "bg"),
    ("fg-secondary", "surface"),
    ("fg-muted", "bg"),
    ("fg-muted", "surface"),
    ("fg-muted", "surface-raised"),
    ("fg-muted", "surface-sunken"),
    ("on-action", "action"),
    ("on-action", "action-hover"),
    ("on-action-subtle", "action-subtle"),
    ("link", "bg"),
    ("link", "surface"),
    ("on-evidence-marker", "evidence-marker"),
    ("on-evidence-marker-active", "evidence-marker-active"),
)

# Control outlines, focus rings and evidence boxes (WCAG 1.4.11).
_NON_TEXT_PAIRS = (
    ("border-control", "bg"),
    ("border-control", "surface"),
    ("focus", "bg"),
    ("focus", "surface"),
    ("evidence-stroke", "surface"),
)

_GENERIC_FAMILIES = frozenset({
    "monospace",
    "sans-serif",
    "serif",
    "system-ui",
    "ui-monospace",
    "ui-sans-serif",
    "ui-serif",
})

# tokens.json typography key, tokens.css suffix, Tailwind --text-* suffix.
_TYPE_PROPERTIES = (
    ("fontSize", "size", ""),
    ("lineHeight", "line-height", "--line-height"),
    ("fontWeight", "weight", "--font-weight"),
    ("letterSpacing", "tracking", "--letter-spacing"),
)

_HEADER = """/*
 * {title}
 * Generated by design-system/build_tokens.py from tokens.json.
 * Do not edit by hand: change tokens.json and run the script.
 */
"""

# How many dark overrides nested inside light ones the dark: variant
# resolves (dark, then dark > light > dark, ...). Each level adds a rule.
_THEME_NESTING_DEPTH = 3

_BASE_LAYER = """@layer base {
  html {
    background-color: var(--rf-bg);
    color: var(--rf-fg);
  }

  :focus-visible {
    outline: 2px solid var(--rf-focus);
    outline-offset: 2px;
  }
}
"""


def load_tokens(path=TOKENS_PATH):
    """Reads a tokens file.

    Args:
        path: Location of the tokens JSON file.

    Returns:
        The parsed token tree.
    """
    with open(path, encoding="utf-8") as tokens_file:
        return json.load(tokens_file)


def _children(group):
    """Returns the (name, node) pairs of a group, skipping $-keys."""
    return [(key, node) for key, node in group.items()
            if not key.startswith("$")]


def _dark(token):
    """Returns the dark-theme value stored in a token's extensions."""
    return token["$extensions"][EXTENSION_KEY]["dark"]


def iter_palette_colors(tokens):
    """Yields every palette color.

    Args:
        tokens: The parsed token tree.

    Yields:
        (name, value) pairs such as ("cobalt-500", "#2d4fd6").
    """
    for family, steps in _children(tokens["color"]):
        for step, token in _children(steps):
            yield f"{family}-{step}", token["$value"]


def iter_theme_colors(tokens):
    """Yields every theme and status color with both theme values.

    Args:
        tokens: The parsed token tree.

    Yields:
        (name, light, dark) triples such as ("bg", "#f2f3f5", "#0e1116").
        Status colors are named "<status>-<part>", such as "approved-bg".
    """
    for name, token in _children(tokens["theme"]):
        yield name, token["$value"], _dark(token)
    for status, parts in _children(tokens["status"]):
        for part, token in _children(parts):
            yield f"{status}-{part}", token["$value"], _dark(token)


def _luminance(hex_color):
    """Returns the WCAG relative luminance of a #rrggbb color."""
    channels = [int(hex_color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [
        c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
        for c in channels
    ]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast_ratio(first, second):
    """Computes the WCAG 2.x contrast ratio between two colors.

    Args:
        first: A #rrggbb color.
        second: Another #rrggbb color.

    Returns:
        The ratio, from 1.0 (identical) to 21.0 (black on white).
    """
    lighter, darker = sorted(
        (_luminance(first), _luminance(second)), reverse=True
    )
    return (lighter + 0.05) / (darker + 0.05)


def contrast_requirements(tokens):
    """Lists the color pairs that must meet a minimum contrast.

    Args:
        tokens: The parsed token tree.

    Returns:
        (foreground, background, minimum ratio) triples of color names.
    """
    pairs = [(fg, bg, TEXT_CONTRAST) for fg, bg in _TEXT_PAIRS]
    pairs += [(fg, bg, NON_TEXT_CONTRAST) for fg, bg in _NON_TEXT_PAIRS]
    for status, _ in _children(tokens["status"]):
        pairs.append((f"{status}-fg", f"{status}-bg", TEXT_CONTRAST))
    return pairs


def find_contrast_failures(tokens):
    """Checks every contrast requirement in the light and dark themes.

    A transparent background is measured against the surface color, which
    is what shows through it.

    Args:
        tokens: The parsed token tree.

    Returns:
        One message per failing pair and theme; empty when all pass.
    """
    colors = {
        name: (light, dark)
        for name, light, dark in iter_theme_colors(tokens)
    }
    failures = []
    for fg, bg, minimum in contrast_requirements(tokens):
        for index, theme in enumerate(("light", "dark")):
            background = colors[bg][index]
            if background == "transparent":
                background = colors["surface"][index]
            ratio = contrast_ratio(colors[fg][index], background)
            if ratio < minimum:
                failures.append(
                    f"{fg} on {bg} ({theme}): {ratio:.2f}:1,"
                    f" needs {minimum}:1"
                )
    return failures


def _css_color(value):
    """Lower-cases a hex color and shortens it to 3 digits when lossless."""
    value = value.lower()
    if re.fullmatch(r"#([0-9a-f])\1([0-9a-f])\2([0-9a-f])\3", value):
        return "#" + value[1] + value[3] + value[5]
    return value


def _font_stack(families):
    """Formats a font family list, quoting every non-generic name."""
    return ", ".join(
        family if family in _GENERIC_FAMILIES else f"'{family}'"
        for family in families
    )


def _dark_variant():
    """Builds a dark: variant that follows the nearest data-theme.

    An element is dark when its nearest data-theme (on itself or an
    ancestor) is dark, or when it has none and the OS prefers dark; this is
    how light-dark() resolves the colors. CSS cannot select the nearest
    ancestor, so each rule matches a chain of alternating overrides ending
    in dark and excludes anything inside a light override below that chain.

    Returns:
        The @custom-variant block.
    """
    dark = "[data-theme='dark']"
    light = "[data-theme='light']"
    rules = []
    chain = dark
    for _ in range(_THEME_NESTING_DEPTH):
        rules.append(
            f"  &:where({chain}, {chain} *)"
            f":not(:where({chain} {light}, {chain} {light} *)) {{\n"
            "    @slot;\n"
            "  }\n"
        )
        chain = f"{chain} {light} {dark}"
    rules.append(
        "  @media (prefers-color-scheme: dark) {\n"
        f"    &:where(:not({light}, {light} *)) {{\n"
        "      @slot;\n"
        "    }\n"
        "  }\n"
    )
    return "@custom-variant dark {\n" + "\n".join(rules) + "}\n"


def render_tokens_css(tokens):
    """Renders tokens.css: every token as a --rf-* custom property.

    Args:
        tokens: The parsed token tree.

    Returns:
        The stylesheet text.
    """
    lines = [_HEADER.format(title="Assay design tokens for RAG Foundry."),
             ":root {",
             "  color-scheme: light dark;",
             "",
             "  /* Palette. Prefer the theme colors below in components. */"]
    for name, value in iter_palette_colors(tokens):
        lines.append(f"  --rf-{name}: {_css_color(value)};")

    lines += ["", "  /* Theme and status colors: light-dark(light, dark). */"]
    for name, light, dark in iter_theme_colors(tokens):
        lines.append(
            f"  --rf-{name}:"
            f" light-dark({_css_color(light)}, {_css_color(dark)});"
        )

    lines += ["", "  /* Fonts. */"]
    for name, token in _children(tokens["font"]):
        lines.append(f"  --rf-font-{name}: {_font_stack(token['$value'])};")

    lines += ["", "  /* Type scale. */"]
    for name, token in _children(tokens["text"]):
        for key, suffix, _ in _TYPE_PROPERTIES:
            if key in token["$value"]:
                lines.append(
                    f"  --rf-text-{name}-{suffix}: {token['$value'][key]};"
                )

    lines += ["", "  /* Space, sizes, radii and shadows. */"]
    for group in ("space", "size", "radius", "shadow"):
        for name, token in _children(tokens[group]):
            lines.append(f"  --rf-{group}-{name}: {token['$value']};")

    lines += ["}",
              "",
              "[data-theme='light'] {",
              "  color-scheme: light;",
              "}",
              "",
              "[data-theme='dark'] {",
              "  color-scheme: dark;",
              "}"]
    return "\n".join(lines) + "\n"


def render_tailwind_css(tokens):
    """Renders tailwind.css: a Tailwind v4 theme over the --rf-* properties.

    Tailwind's default colors, type sizes, radii and shadows are removed so
    only Assay values are available as utilities.

    Args:
        tokens: The parsed token tree.

    Returns:
        The stylesheet text.
    """
    lines = [_HEADER.format(title="Assay theme for Tailwind CSS v4."),
             "@import './tokens.css';",
             "",
             _dark_variant(),
             "@theme {",
             "  --color-*: initial;",
             "  --text-*: initial;",
             "  --radius-*: initial;",
             "  --shadow-*: initial;",
             "}",
             "",
             "@theme inline {"]
    for name, _ in iter_palette_colors(tokens):
        lines.append(f"  --color-{name}: var(--rf-{name});")
    for name, _, _ in iter_theme_colors(tokens):
        lines.append(f"  --color-{name}: var(--rf-{name});")
    lines.append("")
    for name, _ in _children(tokens["font"]):
        lines.append(f"  --font-{name}: var(--rf-font-{name});")
    lines.append("")
    for name, token in _children(tokens["text"]):
        for key, suffix, tailwind_suffix in _TYPE_PROPERTIES:
            if key in token["$value"]:
                lines.append(
                    f"  --text-{name}{tailwind_suffix}:"
                    f" var(--rf-text-{name}-{suffix});"
                )
    lines += ["", "  --spacing: var(--rf-space-unit);", ""]
    for group in ("radius", "shadow"):
        for name, _ in _children(tokens[group]):
            lines.append(f"  --{group}-{name}: var(--rf-{group}-{name});")
    lines += ["}", "", _BASE_LAYER]
    return "\n".join(lines)


def main(argv=None):
    """Regenerates or checks tokens.css and tailwind.css.

    Args:
        argv: Command-line arguments, without the program name.

    Returns:
        0 on success; 1 if a contrast requirement fails or, with --check,
        if a generated file is missing or out of date.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale files instead of writing them",
    )
    parser.add_argument(
        "--out-dir",
        type=pathlib.Path,
        default=DESIGN_DIR,
        help="directory for the generated files (default: design-system)",
    )
    args = parser.parse_args(argv)

    tokens = load_tokens()
    failures = find_contrast_failures(tokens)
    if failures:
        print("Contrast requirements not met:", file=sys.stderr)
        for failure in failures:
            print(f"  {failure}", file=sys.stderr)
        return 1

    outputs = {
        "tokens.css": render_tokens_css(tokens),
        "tailwind.css": render_tailwind_css(tokens),
    }
    stale = []
    for name, content in outputs.items():
        path = args.out_dir / name
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        if args.check:
            stale.append(name)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print(
            f"Out of date: {', '.join(stale)}."
            " Run: python design-system/build_tokens.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
